#!/usr/bin/env ruby

# SEMPRE depends on several library/data files into *lib*.  Run this script to
# copy those dependencies to your local directory.  This allows you to run
# SEMPRE from anywhere.  This file consists of a set of modules (which loosely
# correspond to the code modules).

# The master copy of these dependencies are stored on the Stanford NLP
# machines.

$version = '2.0'
$isPublic = true


def isZip(name)
  # Directories are zipped
  name.end_with?('.exec') or name !~ /\./
end

# - Download the dependencies from the Stanford SEMPRE servers.
def pull(sourcePath, dir=nil, opts={})
  puts sourcePath
  destDir = 'lib' + (dir ? '/' + dir : '')
  system "mkdir -p #{destDir}"

  name = File.basename(sourcePath)
  ext = isZip(name) ? '.zip' : ''

  if $isPublic
    # Download url => localPath
    url = 'http://nlp.stanford.edu/software/sempre/dependencies-' + $version + sourcePath + ext
    localPath = destDir + '/' + name + ext
    system "mkdir -p #{File.dirname(localPath)}" or exit 1
    system "wget -c '#{url}' -O #{localPath}" or exit 1
    # Unzip localPath to destDir if it's a zip file
    if isZip(name)
      system "cd #{File.dirname(localPath)} && unzip #{File.basename(localPath)}" or exit 1
      system "rm #{localPath}" or exit 1
    end
  else
  end
end

def pullAfs(sourcePath, dir=nil, opts={})
    puts sourcePath
  destDir = 'lib' + (dir ? '/' + dir : '')
  system "mkdir -p #{destDir}"

  name = File.basename(sourcePath)
  ext = isZip(name) ? '.zip' : ''

  if $isPublic
    # Download url => localPath
    url = 'https://web.stanford.edu/~gcampagn/sempre/' + sourcePath + ext
    localPath = destDir + '/' + name + ext
    system "mkdir -p #{File.dirname(localPath)}" or exit 1
    system "wget -c '#{url}' -O #{localPath}" or exit 1
    # Unzip localPath to destDir if it's a zip file
    if isZip(name)
      system "cd #{File.dirname(localPath)} && unzip #{File.basename(localPath)}" or exit 1
      system "rm #{localPath}" or exit 1
    end
  else
  end
end

# source: path to master git repository
def updateGit(source)
  dir = File.basename(source.sub(/\.git$/, ''))
  if File.exists?(dir)
    system 'cd '+dir+' && git pull' or exit 1
  else
    system 'git clone ' + source or exit 1
  end
end

def downloadExec(path)
  ['options.map', 'params', 'grammar'].each { |file|
    if File.exists?(path+'/'+file)
      pull(path+'/'+file, 'models/'+File.basename(path))
    end
  }
end

$modules = []
def addModule(name, description, func)
  $modules << [name, description, func]
end

############################################################

addModule('core', 'Core utilities (need to compile)', lambda {
  # fig: options parsing, experiment management, utils
  updateGit('https://github.com/percyliang/fig')
  system 'make -C fig' or exit 1
  system 'mkdir -p lib && cd lib && ln -sf ../fig/fig.jar' or exit 1

  # Google libraries
  pull('/u/nlp/data/semparse/resources/guava-14.0.1.jar')

  # TestNG -- testing framework
  pull('/u/nlp/data/semparse/resources/testng-6.8.5.jar')
  pull('/u/nlp/data/semparse/resources/jcommander-1.30.jar')

  # Checkstyle: make sure code looks fine
  pull('/u/nlp/data/semparse/resources/checkstyle')

  # JSON
  pull('/u/nlp/data/semparse/resources/jackson-core-2.2.0.jar')
  pull('/u/nlp/data/semparse/resources/jackson-annotations-2.2.0.jar')
  pull('/u/nlp/data/semparse/resources/jackson-databind-2.2.0.jar')
})

addModule('corenlp', 'Stanford CoreNLP (code and modules)', lambda {
  pullAfs('stanford-corenlp-full-2015-12-09.zip', '', {:symlink => true})
  if not File.exists?('lib/stanford-corenlp-full-2015-12-09')
    system "cd lib && unzip stanford-corenlp-full-2015-12-09.zip" or exit 1
  end
  ['stanford-corenlp-3.6.0.jar', 'stanford-corenlp-3.6.0-models.jar', 'joda-time.jar', 'jollyday.jar', 'ejml-0.23.jar', 'javax.json.jar', 'protobuf.jar', 'slf4j-api.jar', 'slf4j-simple.jar', 'xom.jar'].each { |file|
    system "ln -sfv stanford-corenlp-full-2015-12-09/#{file} lib" or exit 1
  }
  pullAfs('stanford-corenlp-caseless-2015-04-20-models.jar', '', {:symlink => true})
})

addModule('corenlp-chinese', 'Stanford CoreNLP Chinese models', lambda {
  pullAfs('stanford-chinese-corenlp-2016-01-19-models.jar')
})

addModule('corenlp-german', 'Stanford CoreNLP German models', lambda {
  pullAfs('stanford-german-2016-01-19-models.jar')
})

addModule('corenlp-french', 'Stanford CoreNLP French models', lambda {
  pullAfs('stanford-french-corenlp-2016-01-14-models.jar')
})

addModule('corenlp-spanish', 'Stanford CoreNLP Spanish models', lambda {
  pullAfs('stanford-spanish-corenlp-2015-10-14-models.jar')
})

addModule('thingtalk', 'ThingTalk & Sabrina', lambda {
  pullAfs('commons-dbcp2-2.1.1.jar')
  pullAfs('commons-dbcp2-2.1.1-javadoc.jar')
  pullAfs('commons-logging-1.2.jar')
  pullAfs('commons-logging-1.2-javadoc.jar')
  pullAfs('commons-pool2-2.4.2.jar')
  pullAfs('commons-pool2-2.4.2-javadoc.jar')
  pullAfs('mysql-connector-java.jar')
})

############################################################

if ARGV.size == 0
  puts "#{$0} <module-1> ... <module-n>"
  puts
  puts "Modules:"
  $modules.each { |name,description,func|
    puts "  #{name}: #{description}"
  }
end

$modules.each { |name,description,func|
  if ARGV.index(name)
    puts "===== Downloading #{name}: #{description}"
    func.call
  end
}
